-- Active: 1757059462497@@127.0.0.1@3306@todo_app
CREATE DATABASE IF NOT EXISTS TODO_APP;

USE TODO_APP;

CREATE TABLE IF NOT EXISTS TODOS (
    id INT(11) NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    title VARCHAR(25),
    note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO
    todos (ID, TITLE, NOTE)
VALUES (
        1,
        "TESTING",
        "THIS IS TESTING OF THE DATABSE "
    );

INSERT INTO
    todos (ID, TITLE, NOTE)
VALUES (
        3,
        "TESTING3",
        "THIS IS 3 titleTESTING OF THE DATABSE "
    );